import { useEffect, useRef } from "react";
import type { ContentBlock, Message, ModelInfo } from "@chat/shared";

function Blocks({ blocks }: { blocks: ContentBlock[] }) {
  return (
    <>
      {blocks.map((b, i) => {
        switch (b.type) {
          case "text":
            return <div key={i} className="bubble">{b.text}</div>;
          case "image":
          case "document":
            return (
              <span key={i} className="attachment-pill">
                {b.type === "image" ? "🖼️" : "📄"} {b.name}
              </span>
            );
          case "toolUse":
            return (
              <div key={i} className="tool-chip">
                🔎 Searching chat history…
              </div>
            );
          case "toolResult":
            return (
              <div key={i} className="tool-chip">
                🔎 History search → {b.content.length} result
                {b.content.length === 1 ? "" : "s"}
              </div>
            );
          default:
            return null;
        }
      })}
    </>
  );
}

function ModelAvatar() {
  return (
    <span className="avatar" aria-hidden="true">
      <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 2l2.6 6.8L21 11.5l-6.4 2.7L12 22l-2.6-7.8L3 11.5l6.4-2.7z" />
      </svg>
    </span>
  );
}

export function MessageList({
  messages,
  streamingText,
  toolStatus,
  models,
}: {
  messages: Message[];
  streamingText: string | null;
  toolStatus: string | null;
  models: ModelInfo[];
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  // Only auto-scroll when the user is already parked at the bottom; if they've
  // scrolled up to read, leave their position alone (streaming deltas would
  // otherwise yank them back down on every frame).
  const stickToBottom = useRef(true);

  const onScroll = () => {
    const el = containerRef.current;
    if (!el) return;
    const distanceFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;
    stickToBottom.current = distanceFromBottom < 80;
  };

  useEffect(() => {
    if (!stickToBottom.current) return;
    const el = containerRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages, streamingText, toolStatus]);

  const labelFor = (modelId: string | null) =>
    models.find((m) => m.id === modelId)?.label ?? "the model";

  // Hide assistant turns that are only tool-use (no visible text) when we also
  // render a tool chip — but keep them so replay shows the search happened.
  const visible = messages.filter(
    (m) =>
      m.blocks.length > 0 &&
      !(
        m.role === "user" &&
        m.blocks.every((b) => b.type === "toolResult")
      )
  );

  return (
    <div className="messages" ref={containerRef} onScroll={onScroll}>
      {visible.length === 0 && !streamingText && (
        <div className="empty">Send a message to start the conversation.</div>
      )}
      {visible.map((m) =>
        m.role === "assistant" ? (
          <div key={m.id} className="msg assistant">
            <div className="assistant-row">
              <ModelAvatar />
              <div className="assistant-col">
                <Blocks blocks={m.blocks} />
                <div className="msg-foot">
                  Response generated by {labelFor(m.modelId)}
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div key={m.id} className="msg user">
            <Blocks blocks={m.blocks} />
          </div>
        )
      )}
      {toolStatus && (
        <div className="msg assistant">
          <div className="tool-chip">{toolStatus}</div>
        </div>
      )}
      {streamingText !== null && (
        <div className="msg assistant">
          <div className="assistant-row">
            <ModelAvatar />
            <div className="assistant-col">
              <div className="bubble">
                {streamingText === "" ? (
                  <span className="typing-dots">
                    <span /><span /><span />
                  </span>
                ) : (
                  <>
                    {streamingText}
                    <span className="muted">▌</span>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
